[package]
name = "b25-sys"
version = "1.0.0"
authors = ["maleicacid <maleicacid824+dev@gmail.com>"]
edition = "2021"
description = "b25-sys is more convenient Rust wrapper for libaribb25."
build = "build.rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/kazuki0824/recisdb-rs.git"
keywords = ["dtv", "japan", "broadcast", "b25"]

[dependencies]
pin-project-lite = "^0.2.9"
log = "^0.4.17"
tail_cbc = { version = "^0.1.2", optional = true }
cbc-mac = { version = "^0.1.1", optional = true }

[build-dependencies]
pkg-config = "0.3.25"
cmake = "0.1.45"
